# Generated by Django 2.2.2 on 2019-06-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('season', models.CharField(max_length=8)),
                ('type', models.CharField(max_length=1)),
                ('date_time', models.DateTimeField()),
                ('away_team_id', models.IntegerField()),
                ('home_team_id', models.IntegerField()),
                ('away_goals', models.IntegerField()),
                ('home_goals', models.IntegerField()),
                ('outcome', models.CharField(max_length=12)),
                ('home_rink_side_start', models.CharField(max_length=5)),
                ('venue', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Player_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('primaryPosition', models.CharField(max_length=30)),
                ('timeOnIce', models.CharField(max_length=10)),
                ('assists', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('shots', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('powerPlayGoals', models.IntegerField()),
                ('powerPlayAssists', models.IntegerField()),
                ('penaltyMinutes', models.IntegerField()),
                ('faceOffWins', models.IntegerField()),
                ('faceoffTaken', models.IntegerField()),
                ('takeaways', models.IntegerField()),
                ('giveaways', models.IntegerField()),
                ('shortHandedGoals', models.IntegerField()),
                ('shortHandedAssists', models.IntegerField()),
                ('blocked', models.IntegerField()),
                ('plusMinus', models.IntegerField()),
                ('evenTimeOnIce', models.CharField(max_length=10)),
                ('powerPlayTimeOnIce', models.CharField(max_length=10)),
                ('shortHandedTimeOnIce', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Plays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_id', models.CharField(max_length=14)),
                ('game_id', models.IntegerField()),
                ('play_num', models.IntegerField()),
                ('team_id_for', models.IntegerField()),
                ('team_id_against', models.IntegerField()),
                ('event', models.CharField(max_length=30)),
                ('secondaryType', models.CharField(max_length=50)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('period', models.IntegerField()),
                ('periodType', models.CharField(max_length=50)),
                ('periodTime', models.TimeField()),
                ('periodTimeRemaining', models.TimeField()),
                ('dateTime', models.DateTimeField()),
                ('goals_away', models.IntegerField()),
                ('goals_home', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('st_x', models.IntegerField()),
                ('st_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_Plays_Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_id', models.CharField(max_length=14)),
                ('game_id', models.IntegerField()),
                ('play_num', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('player_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Team_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('pim', models.IntegerField()),
                ('shots', models.IntegerField()),
                ('powerPlayPercentage', models.FloatField()),
                ('powerPlayGoals', models.IntegerField()),
                ('powerPlayOpportunities', models.IntegerField()),
                ('faceOffWinPercentage', models.FloatField()),
                ('blocked', models.IntegerField()),
                ('takeaways', models.IntegerField()),
                ('giveaways', models.IntegerField()),
                ('hits', models.IntegerField()),
            ],
        ),
    ]
